CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "ActivityLog" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Screen" text NOT NULL,
        "Action" text NOT NULL,
        "Details" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ActivityLog" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Componente" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Ponderacion" real NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Componente" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Condicion" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Color" text NOT NULL,
        "Nivel" integer NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Condicion" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "CriterioCumpleFrecuencia" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "ValorMinimo" integer NOT NULL,
        "ValorMaximo" integer NOT NULL,
        "Color" text NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_CriterioCumpleFrecuencia" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Criticidad" (
        "ID" integer NOT NULL,
        "Nombre" text NOT NULL,
        "Nivel" integer NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_Criticidad" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "ExceptionData" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "AppVersion" text NOT NULL,
        "Message" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExceptionData" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Faena" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Logo" text NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Faena" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "FotoInspeccion" (
        "ID" text NOT NULL,
        "Archivo" text NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FotoInspeccion" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "MedicionEspesor" (
        "ID" text NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "FechaUltimaModificacion" timestamp with time zone,
        "Inspector" text NOT NULL,
        "EspesorMinimo" real NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Tonelaje" real,
        "EmpalmeID" integer NOT NULL,
        "OT" text NOT NULL,
        "Comentario" text,
        "ComentarioReporte" text,
        "Mediciones" real[] NOT NULL,
        "DistanciasMediciones" real[] NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MedicionEspesor" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "ModoFalla" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ModoFalla" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Planta" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(25) NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        "DiagramaFlujo" text,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Planta" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "ReceptoresReporteFlash" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" text NOT NULL,
        "Nombre" text NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_ReceptoresReporteFlash" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "ReporteFlash" (
        "ID" text NOT NULL,
        "FechaEnvio" timestamp with time zone NOT NULL,
        "Destinatarios" text NOT NULL,
        "Asunto" text NOT NULL,
        "CuerpoMensaje" text NOT NULL,
        "Estatus" integer NOT NULL,
        "ErrorMensaje" text NOT NULL,
        "IntentosEnvio" integer NOT NULL,
        "UrlReporte" text NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ReporteFlash" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Usuario" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" text NOT NULL,
        "Nombre" text NOT NULL,
        "Password" text NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Usuario" PRIMARY KEY ("ID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "UsuarioPermiso" (
        "UsuarioID" integer NOT NULL,
        "Permiso" integer NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UsuarioPermiso" PRIMARY KEY ("UsuarioID", "Permiso")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Area" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(25) NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        "PlantaID" integer NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Area" PRIMARY KEY ("ID"),
        CONSTRAINT "FK_Area_Planta_PlantaID" FOREIGN KEY ("PlantaID") REFERENCES "Planta" ("ID") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Equipo" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(25) NOT NULL,
        "TipoCorrea" character varying(250) NOT NULL,
        "DesarrolloMts" real NOT NULL,
        "AnchoMM" real NOT NULL,
        "EspesorOriginalCubiertaCargaMM" real NOT NULL,
        "EspesorMinimoCubiertaCargaMM" real NOT NULL,
        "CantidadPuntosMedicion" integer NOT NULL,
        "DistanciaMedicion" real NOT NULL,
        "CantidadEmpalmes" integer NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "Activo" boolean NOT NULL,
        "Frecuencia" integer NOT NULL,
        "AreaID" integer NOT NULL,
        "CriticidadID" integer NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Equipo" PRIMARY KEY ("ID"),
        CONSTRAINT "FK_Equipo_Area_AreaID" FOREIGN KEY ("AreaID") REFERENCES "Area" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_Equipo_Criticidad_CriticidadID" FOREIGN KEY ("CriticidadID") REFERENCES "Criticidad" ("ID") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Inspeccion" (
        "ID" text NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "FechaUltimaModificacion" timestamp with time zone,
        "Inspector" text NOT NULL,
        "NumeroAviso" text,
        "Descripcion" text NOT NULL,
        "OT" text NOT NULL,
        "CausaRaiz" text,
        "IntervencionRecomendada" text,
        "Mitigacion" text,
        "EsReporteFlash" boolean NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "EquipoID" integer NOT NULL,
        "ComponenteID" integer NOT NULL,
        "CondicionID" integer NOT NULL,
        "ModoFallaID" integer NOT NULL,
        "ReporteFlashID" integer,
        "Foto1" text,
        "Foto2" text,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Inspeccion" PRIMARY KEY ("ID"),
        CONSTRAINT "FK_Inspeccion_Componente_ComponenteID" FOREIGN KEY ("ComponenteID") REFERENCES "Componente" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_Inspeccion_Condicion_CondicionID" FOREIGN KEY ("CondicionID") REFERENCES "Condicion" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_Inspeccion_Equipo_EquipoID" FOREIGN KEY ("EquipoID") REFERENCES "Equipo" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_Inspeccion_ModoFalla_ModoFallaID" FOREIGN KEY ("ModoFallaID") REFERENCES "ModoFalla" ("ID") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Tramo" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(25) NOT NULL,
        "FechaInstalacion" timestamp with time zone NOT NULL,
        "Frecuencia" integer NOT NULL,
        "FechaCambioFrecuencia" timestamp with time zone NOT NULL,
        "FechaCambioPlanificado" timestamp with time zone,
        "FechaCambioEfectivo" timestamp with time zone,
        "Activo" boolean NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "EquipoID" integer NOT NULL,
        "Index" integer NOT NULL,
        CONSTRAINT "PK_Tramo" PRIMARY KEY ("ID"),
        CONSTRAINT "FK_Tramo_Equipo_EquipoID" FOREIGN KEY ("EquipoID") REFERENCES "Equipo" ("ID") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE TABLE "Empalme" (
        "ID" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(25) NOT NULL,
        "EquipoID" integer NOT NULL,
        "TramoInicioID" integer,
        "TramoTerminoID" integer,
        "Index" integer NOT NULL,
        "Activo" boolean NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Empalme" PRIMARY KEY ("ID"),
        CONSTRAINT "FK_Empalme_Equipo_EquipoID" FOREIGN KEY ("EquipoID") REFERENCES "Equipo" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_Empalme_Tramo_TramoInicioID" FOREIGN KEY ("TramoInicioID") REFERENCES "Tramo" ("ID") ON DELETE RESTRICT,
        CONSTRAINT "FK_Empalme_Tramo_TramoTerminoID" FOREIGN KEY ("TramoTerminoID") REFERENCES "Tramo" ("ID") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Area_LastModifiedDate" ON "Area" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Area_PlantaID" ON "Area" ("PlantaID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Componente_LastModifiedDate" ON "Componente" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Condicion_LastModifiedDate" ON "Condicion" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Empalme_EquipoID" ON "Empalme" ("EquipoID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Empalme_LastModifiedDate" ON "Empalme" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Empalme_TramoInicioID" ON "Empalme" ("TramoInicioID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Empalme_TramoTerminoID" ON "Empalme" ("TramoTerminoID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Equipo_AreaID" ON "Equipo" ("AreaID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Equipo_CriticidadID" ON "Equipo" ("CriticidadID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Equipo_LastModifiedDate" ON "Equipo" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_FotoInspeccion_LastModifiedDate" ON "FotoInspeccion" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Inspeccion_ComponenteID" ON "Inspeccion" ("ComponenteID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Inspeccion_CondicionID" ON "Inspeccion" ("CondicionID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Inspeccion_EquipoID" ON "Inspeccion" ("EquipoID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Inspeccion_Fecha_LastModifiedDate" ON "Inspeccion" ("Fecha", "LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Inspeccion_ModoFallaID" ON "Inspeccion" ("ModoFallaID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_MedicionEspesor_LastModifiedDate" ON "MedicionEspesor" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_ModoFalla_LastModifiedDate" ON "ModoFalla" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Planta_LastModifiedDate" ON "Planta" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Tramo_EquipoID" ON "Tramo" ("EquipoID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    CREATE INDEX "IX_Usuario_LastModifiedDate" ON "Usuario" ("LastModifiedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251128181207_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251128181207_InitialCreate', '9.0.7');
    END IF;
END $EF$;
COMMIT;

