-- Script para ejecutar una sola vez en Render y recrear el esquema desde InitialCreate.
-- Usa DROP ... CASCADE para limpiar cualquier rastro previo y luego crea todo nuevamente.
BEGIN;

-- Limpieza en orden inverso para no topar dependencias.
DROP TABLE IF EXISTS "Empalme" CASCADE;
DROP TABLE IF EXISTS "Tramo" CASCADE;
DROP TABLE IF EXISTS "Inspeccion" CASCADE;
DROP TABLE IF EXISTS "Equipo" CASCADE;
DROP TABLE IF EXISTS "Area" CASCADE;
DROP TABLE IF EXISTS "UsuarioPermiso" CASCADE;
DROP TABLE IF EXISTS "Usuario" CASCADE;
DROP TABLE IF EXISTS "ReporteFlash" CASCADE;
DROP TABLE IF EXISTS "ReceptoresReporteFlash" CASCADE;
DROP TABLE IF EXISTS "Planta" CASCADE;
DROP TABLE IF EXISTS "ModoFalla" CASCADE;
DROP TABLE IF EXISTS "MedicionEspesor" CASCADE;
DROP TABLE IF EXISTS "FotoInspeccion" CASCADE;
DROP TABLE IF EXISTS "Faena" CASCADE;
DROP TABLE IF EXISTS "ExceptionData" CASCADE;
DROP TABLE IF EXISTS "Criticidad" CASCADE;
DROP TABLE IF EXISTS "CriterioCumpleFrecuencia" CASCADE;
DROP TABLE IF EXISTS "Condicion" CASCADE;
DROP TABLE IF EXISTS "Componente" CASCADE;
DROP TABLE IF EXISTS "ActivityLog" CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;

-- Tablas
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "ActivityLog" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Screen" text NOT NULL,
    "Action" text NOT NULL,
    "Details" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ActivityLog" PRIMARY KEY ("ID")
);

CREATE TABLE "Componente" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Ponderacion" real NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Componente" PRIMARY KEY ("ID")
);

CREATE TABLE "Condicion" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Color" text NOT NULL,
    "Nivel" integer NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Condicion" PRIMARY KEY ("ID")
);

CREATE TABLE "CriterioCumpleFrecuencia" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ValorMinimo" integer NOT NULL,
    "ValorMaximo" integer NOT NULL,
    "Color" text NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_CriterioCumpleFrecuencia" PRIMARY KEY ("ID")
);

CREATE TABLE "Criticidad" (
    "ID" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Nivel" integer NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Criticidad" PRIMARY KEY ("ID")
);

CREATE TABLE "ExceptionData" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "AppVersion" text NOT NULL,
    "Message" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExceptionData" PRIMARY KEY ("ID")
);

CREATE TABLE "Faena" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Logo" text NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Faena" PRIMARY KEY ("ID")
);

CREATE TABLE "FotoInspeccion" (
    "ID" text NOT NULL,
    "Archivo" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FotoInspeccion" PRIMARY KEY ("ID")
);

CREATE TABLE "MedicionEspesor" (
    "ID" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "FechaUltimaModificacion" timestamp with time zone,
    "Inspector" text NOT NULL,
    "EspesorMinimo" real NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Tonelaje" real,
    "EmpalmeID" integer NOT NULL,
    "OT" text NOT NULL,
    "Comentario" text,
    "ComentarioReporte" text,
    "Mediciones" real[] NOT NULL,
    "DistanciasMediciones" real[] NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MedicionEspesor" PRIMARY KEY ("ID")
);

CREATE TABLE "ModoFalla" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ModoFalla" PRIMARY KEY ("ID")
);

CREATE TABLE "Planta" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(25) NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    "DiagramaFlujo" text,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Planta" PRIMARY KEY ("ID")
);

CREATE TABLE "ReceptoresReporteFlash" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "Nombre" text NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_ReceptoresReporteFlash" PRIMARY KEY ("ID")
);

CREATE TABLE "ReporteFlash" (
    "ID" text NOT NULL,
    "FechaEnvio" timestamp with time zone NOT NULL,
    "Destinatarios" text NOT NULL,
    "Asunto" text NOT NULL,
    "CuerpoMensaje" text NOT NULL,
    "Estatus" integer NOT NULL,
    "ErrorMensaje" text NOT NULL,
    "IntentosEnvio" integer NOT NULL,
    "UrlReporte" text NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ReporteFlash" PRIMARY KEY ("ID")
);

CREATE TABLE "Usuario" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Nombre" text NOT NULL,
    "Password" text NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Usuario" PRIMARY KEY ("ID")
);

CREATE TABLE "UsuarioPermiso" (
    "UsuarioID" integer NOT NULL,
    "Permiso" integer NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UsuarioPermiso" PRIMARY KEY ("UsuarioID", "Permiso")
);

CREATE TABLE "Area" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(25) NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    "PlantaID" integer NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Area" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Area_Planta_PlantaID" FOREIGN KEY ("PlantaID") REFERENCES "Planta" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Equipo" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(25) NOT NULL,
    "TipoCorrea" character varying(250) NOT NULL,
    "DesarrolloMts" real NOT NULL,
    "AnchoMM" real NOT NULL,
    "EspesorOriginalCubiertaCargaMM" real NOT NULL,
    "EspesorMinimoCubiertaCargaMM" real NOT NULL,
    "CantidadPuntosMedicion" integer NOT NULL,
    "DistanciaMedicion" real NOT NULL,
    "CantidadEmpalmes" integer NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    "Frecuencia" integer NOT NULL,
    "AreaID" integer NOT NULL,
    "CriticidadID" integer NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Equipo" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Equipo_Area_AreaID" FOREIGN KEY ("AreaID") REFERENCES "Area" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Equipo_Criticidad_CriticidadID" FOREIGN KEY ("CriticidadID") REFERENCES "Criticidad" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Inspeccion" (
    "ID" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "FechaUltimaModificacion" timestamp with time zone,
    "Inspector" text NOT NULL,
    "NumeroAviso" text,
    "Descripcion" text NOT NULL,
    "OT" text NOT NULL,
    "CausaRaiz" text,
    "IntervencionRecomendada" text,
    "Mitigacion" text,
    "EsReporteFlash" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "EquipoID" integer NOT NULL,
    "ComponenteID" integer NOT NULL,
    "CondicionID" integer NOT NULL,
    "ModoFallaID" integer NOT NULL,
    "ReporteFlashID" integer,
    "Foto1" text,
    "Foto2" text,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Inspeccion" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Inspeccion_Componente_ComponenteID" FOREIGN KEY ("ComponenteID") REFERENCES "Componente" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Inspeccion_Condicion_CondicionID" FOREIGN KEY ("CondicionID") REFERENCES "Condicion" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Inspeccion_Equipo_EquipoID" FOREIGN KEY ("EquipoID") REFERENCES "Equipo" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Inspeccion_ModoFalla_ModoFallaID" FOREIGN KEY ("ModoFallaID") REFERENCES "ModoFalla" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Tramo" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(25) NOT NULL,
    "FechaInstalacion" timestamp with time zone NOT NULL,
    "Frecuencia" integer NOT NULL,
    "FechaCambioFrecuencia" timestamp with time zone NOT NULL,
    "FechaCambioPlanificado" timestamp with time zone,
    "FechaCambioEfectivo" timestamp with time zone,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "EquipoID" integer NOT NULL,
    "Index" integer NOT NULL,
    CONSTRAINT "PK_Tramo" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Tramo_Equipo_EquipoID" FOREIGN KEY ("EquipoID") REFERENCES "Equipo" ("ID") ON DELETE CASCADE
);

CREATE TABLE "Empalme" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(25) NOT NULL,
    "EquipoID" integer NOT NULL,
    "TramoInicioID" integer,
    "TramoTerminoID" integer,
    "Index" integer NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Empalme" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Empalme_Equipo_EquipoID" FOREIGN KEY ("EquipoID") REFERENCES "Equipo" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_Empalme_Tramo_TramoInicioID" FOREIGN KEY ("TramoInicioID") REFERENCES "Tramo" ("ID") ON DELETE RESTRICT,
    CONSTRAINT "FK_Empalme_Tramo_TramoTerminoID" FOREIGN KEY ("TramoTerminoID") REFERENCES "Tramo" ("ID") ON DELETE RESTRICT
);

-- Índices
CREATE INDEX "IX_Area_LastModifiedDate" ON "Area" ("LastModifiedDate");
CREATE INDEX "IX_Area_PlantaID" ON "Area" ("PlantaID");
CREATE INDEX "IX_Componente_LastModifiedDate" ON "Componente" ("LastModifiedDate");
CREATE INDEX "IX_Condicion_LastModifiedDate" ON "Condicion" ("LastModifiedDate");
CREATE INDEX "IX_Empalme_EquipoID" ON "Empalme" ("EquipoID");
CREATE INDEX "IX_Empalme_LastModifiedDate" ON "Empalme" ("LastModifiedDate");
CREATE UNIQUE INDEX "IX_Empalme_TramoInicioID" ON "Empalme" ("TramoInicioID");
CREATE UNIQUE INDEX "IX_Empalme_TramoTerminoID" ON "Empalme" ("TramoTerminoID");
CREATE INDEX "IX_Equipo_AreaID" ON "Equipo" ("AreaID");
CREATE INDEX "IX_Equipo_CriticidadID" ON "Equipo" ("CriticidadID");
CREATE INDEX "IX_Equipo_LastModifiedDate" ON "Equipo" ("LastModifiedDate");
CREATE INDEX "IX_FotoInspeccion_LastModifiedDate" ON "FotoInspeccion" ("LastModifiedDate");
CREATE INDEX "IX_Inspeccion_ComponenteID" ON "Inspeccion" ("ComponenteID");
CREATE INDEX "IX_Inspeccion_CondicionID" ON "Inspeccion" ("CondicionID");
CREATE INDEX "IX_Inspeccion_EquipoID" ON "Inspeccion" ("EquipoID");
CREATE INDEX "IX_Inspeccion_Fecha_LastModifiedDate" ON "Inspeccion" ("Fecha", "LastModifiedDate");
CREATE INDEX "IX_Inspeccion_ModoFallaID" ON "Inspeccion" ("ModoFallaID");
CREATE INDEX "IX_MedicionEspesor_LastModifiedDate" ON "MedicionEspesor" ("LastModifiedDate");
CREATE INDEX "IX_ModoFalla_LastModifiedDate" ON "ModoFalla" ("LastModifiedDate");
CREATE INDEX "IX_Planta_LastModifiedDate" ON "Planta" ("LastModifiedDate");
CREATE INDEX "IX_Tramo_EquipoID" ON "Tramo" ("EquipoID");
CREATE INDEX "IX_Usuario_LastModifiedDate" ON "Usuario" ("LastModifiedDate");

-- Registro de migración
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251128181207_InitialCreate', '9.0.7');

COMMIT;
